# -*- coding: utf-8 -*-
"""carbonemission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14thVq9a18X46jo14jPSK5_X6LBlXuJ_T
"""

print("welcome to my wk3 assignment, ai  for software engineering");

import pandas as pd

df = pd.read_csv('/content/historical_emissions.csv')
display(df.head())

df.dropna(subset=['1990'], inplace=True)
display(df.info())

display(df.duplicated().sum())

display(df.isnull().sum())

"""# Task
Analyze emissions trends by country using the data in "/content/historical_emissions.csv".

## Melt the dataframe

### Subtask:
Transform the wide format data (years as columns) into a long format with a 'Year' and 'Emissions' column.

**Reasoning**:
Identify the year columns and melt the DataFrame into long format.
"""

year_columns = [str(year) for year in range(1990, 2019)]
id_vars = ['Country', 'Data source', 'Sector', 'Gas', 'Unit']
df_melted = pd.melt(df, id_vars=id_vars, value_vars=year_columns, var_name='Year', value_name='Emissions')
display(df_melted.head())

"""## Group by country and year

### Subtask:
Group the melted data by 'Country' and 'Year' and sum the emissions for each group.

**Reasoning**:
Group the melted dataframe by 'Country' and 'Year' and calculate the sum of 'Emissions' for each group, then display the head of the resulting dataframe.
"""

df_grouped = df_melted.groupby(['Country', 'Year'])['Emissions'].sum().reset_index()
display(df_grouped.head())

unique_countries = df_grouped['Country'].unique()
display(unique_countries)

"""## Analyze trends

### Subtask:
Calculate or visualize the trends in emissions for each country over the years.

**Reasoning**:
Create a line plot to visualize the emissions trends for a subset of countries over the years using the df_grouped dataframe.
"""

import matplotlib.pyplot as plt

# Filter for a subset of countries (e.g., top emitters)
top_emitters = df_grouped.groupby('Country')['Emissions'].sum().nlargest(5).index
df_subset = df_grouped[df_grouped['Country'].isin(top_emitters)]

plt.figure(figsize=(15, 7))
for country in top_emitters:
    df_country = df_subset[df_subset['Country'] == country]
    plt.plot(df_country['Year'], df_country['Emissions'], label=country)

plt.xlabel('Year')
plt.ylabel('Emissions')
plt.title('Emissions Trends for Top 5 Emitters (1990-2018)')
plt.legend()
plt.grid(True)
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   The top 5 emitting countries were identified based on their total emissions from 1990 to 2018.
*   A visualization was created showing the emissions trends over time for these top 5 countries.

### Insights or Next Steps

*   Further analysis could delve into the reasons behind the observed trends for specific countries, considering factors like economic growth, policy changes, or technological advancements.
*   Investigating emissions trends across different sectors and gases within each country could provide a more granular understanding of the driving forces behind overall emissions.

# Task
Analyze and predict carbon emissions for Kenya, Uganda, Tanzania, and Somalia for the next five years using the dataset located at "/content/historical_emissions.csv".

## Filter data

### Subtask:
Filter the `df_melted` DataFrame to include only the specified East African countries (Kenya, Uganda, Tanzania, Somalia).

**Reasoning**:
Filter the melted dataframe to include only the specified East African countries and display the head of the filtered dataframe.
"""

east_african_countries = ['Kenya', 'Uganda', 'Tanzania', 'Somalia']
df_east_africa = df_melted[df_melted['Country'].isin(east_african_countries)]
display(df_east_africa.head())

"""## Prepare data for time series

### Subtask:
Ensure the data is in a suitable format for time series analysis, likely requiring sorting by year and potentially converting the 'Year' column to a datetime format.

**Reasoning**:
Sort the dataframe by year and convert the year column to datetime objects to prepare for time series analysis, then display the head and info of the updated dataframe.
"""

df_east_africa = df_east_africa.sort_values(by='Year')
df_east_africa['Year'] = pd.to_datetime(df_east_africa['Year'], format='%Y')
display(df_east_africa.head())
display(df_east_africa.info())

"""## Choose and train regression model

### Subtask:
Select an appropriate regression model for time series forecasting and train it on the historical emissions data for the selected countries.

**Reasoning**:
Train a Linear Regression model for each East African country to predict emissions based on the year.
"""

from sklearn.linear_model import LinearRegression

trained_models = {}

for country in east_african_countries:
    df_country = df_east_africa[df_east_africa['Country'] == country].copy()
    X = df_country[['Year']].copy()
    X['Year'] = (X['Year'] - X['Year'].min()).dt.days # Convert datetime to numerical days
    y = df_country['Emissions']

    model = LinearRegression()
    model.fit(X, y)
    trained_models[country] = model

print("Trained models for each country:")
for country, model in trained_models.items():
    print(f"{country}: {model}")

"""## Predict future emissions

### Subtask:
Use the trained model to predict carbon emissions for the next five years for each of the selected countries.

**Reasoning**:
Generate future years, convert them to numerical format, and use the trained models to predict emissions for each country.
"""

from datetime import timedelta

last_year = df_east_africa['Year'].max()
future_years = [last_year + timedelta(days=365 * (i + 1)) for i in range(5)] # Approximate future years

predicted_emissions = {}

for country, model in trained_models.items():
    # Create a DataFrame for future years in the same numerical format as training data
    future_years_df = pd.DataFrame({'Year': future_years})
    min_year = df_east_africa[df_east_africa['Country'] == country]['Year'].min()
    future_years_df['Year'] = (future_years_df['Year'] - min_year).dt.days

    # Predict emissions for future years
    predictions = model.predict(future_years_df[['Year']])
    predicted_emissions[country] = predictions

# Display the predicted emissions
for country, predictions in predicted_emissions.items():
    print(f"Predicted emissions for {country} for the next 5 years:")
    for year, emission in zip(future_years, predictions):
        print(f"  {year.year}: {emission:.2f}")

"""## Present predictions

### Subtask:
Display or visualize the predicted emissions.

**Reasoning**:
Create a DataFrame from the predicted emissions, convert the 'Year' column to datetime, concatenate with the historical data for the East African countries, and then create a line plot to visualize both historical and predicted emissions.
"""

# 1. Create a new DataFrame from the predicted_emissions dictionary
predicted_list = []
for country, predictions in predicted_emissions.items():
    for i, emission in enumerate(predictions):
        predicted_list.append({'Country': country, 'Year': future_years[i].year, 'Emissions': emission})

df_predictions = pd.DataFrame(predicted_list)

# 2. Convert the 'Year' column in the new DataFrame to datetime objects.
df_predictions['Year'] = pd.to_datetime(df_predictions['Year'], format='%Y')

# 3. Concatenate the df_grouped DataFrame (filtered for the East African countries) and the new predictions DataFrame
df_east_africa_grouped = df_grouped[df_grouped['Country'].isin(east_african_countries)].copy()
df_east_africa_grouped['Year'] = pd.to_datetime(df_east_africa_grouped['Year'], format='%Y')

df_combined = pd.concat([df_east_africa_grouped, df_predictions])

# 4. Use matplotlib.pyplot to create a line plot
plt.figure(figsize=(15, 7))
for country in east_african_countries:
    df_country = df_combined[df_combined['Country'] == country]
    plt.plot(df_country['Year'], df_country['Emissions'], label=country)

# 5. Add labels to the x and y axes
plt.xlabel('Year')
plt.ylabel('Emissions/Predicted Emissions')

# 6. Add a title to the plot
plt.title('Historical and Predicted Carbon Emissions for East African Countries')

# 7. Include a legend
plt.legend()

# 8. Add a grid
plt.grid(True)

# 9. Display the plot
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   The predicted emissions for Kenya, Uganda, and Tanzania show a general upward trend over the next five years.
*   Somalia's predicted emissions exhibit a much flatter trend, with only a slight increase projected over the same period.

### Insights or Next Steps

*   Consider exploring more complex time series models (e.g., ARIMA, Prophet) for potentially more accurate predictions, especially if historical data shows non-linear trends or seasonality.
*   Investigate the factors contributing to the differences in predicted emission trends among these countries to inform targeted policy recommendations.

## Choose and Train Decision Tree Model

### Subtask:
Select a Decision Tree regression model and train it on the historical emissions data for each of the selected countries.

**Reasoning**:
Train a Decision Tree Regressor model for each East African country to predict emissions based on the year.
"""

from sklearn.tree import DecisionTreeRegressor

trained_dt_models = {}

for country in east_african_countries:
    df_country = df_east_africa[df_east_africa['Country'] == country].copy()
    X = df_country[['Year']].copy()
    X['Year'] = (X['Year'] - X['Year'].min()).dt.days # Convert datetime to numerical days
    y = df_country['Emissions']

    dt_model = DecisionTreeRegressor()
    dt_model.fit(X, y)
    trained_dt_models[country] = dt_model

print("Trained Decision Tree models for each country:")
for country, model in trained_dt_models.items():
    print(f"{country}: {model}")

"""## Predict Future Emissions

### Subtask:
Use the trained Decision Tree model to predict carbon emissions for the next five years for each of the selected countries.

**Reasoning**:
Generate future years, convert them to numerical format, and use the trained Decision Tree models to predict emissions for each country.
"""

predicted_dt_emissions = {}

for country, model in trained_dt_models.items():
    # Create a DataFrame for future years in the same numerical format as training data
    future_years_df = pd.DataFrame({'Year': future_years})
    min_year = df_east_africa[df_east_africa['Country'] == country]['Year'].min()
    future_years_df['Year'] = (future_years_df['Year'] - min_year).dt.days

    # Predict emissions for future years
    predictions = model.predict(future_years_df[['Year']])
    predicted_dt_emissions[country] = predictions

# Display the predicted emissions
for country, predictions in predicted_dt_emissions.items():
    print(f"Predicted emissions for {country} for the next 5 years (Decision Tree):")
    for year, emission in zip(future_years, predictions):
        print(f"  {year.year}: {emission:.2f}")

"""## Evaluate Model Performance

### Subtask:
Calculate and display the RMSE and R2 scores for both the Linear Regression and Decision Tree models' predictions on the historical data.

**Reasoning**:
Iterate through each country, make predictions on the historical data using both the Linear Regression and Decision Tree models, and calculate and display the RMSE and R2 scores for each model.
"""

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

evaluation_metrics = {}

for country in east_african_countries:
    df_country = df_east_africa[df_east_africa['Country'] == country].copy()
    X_hist = df_country[['Year']].copy()
    X_hist['Year'] = (X_hist['Year'] - X_hist['Year'].min()).dt.days # Convert datetime to numerical days
    y_hist = df_country['Emissions']

    # Evaluate Linear Regression Model
    lr_model = trained_models[country]
    lr_predictions = lr_model.predict(X_hist)
    lr_rmse = np.sqrt(mean_squared_error(y_hist, lr_predictions))
    lr_r2 = r2_score(y_hist, lr_predictions)

    # Evaluate Decision Tree Model
    dt_model = trained_dt_models[country]
    dt_predictions = dt_model.predict(X_hist)
    dt_rmse = np.sqrt(mean_squared_error(y_hist, dt_predictions))
    dt_r2 = r2_score(y_hist, dt_predictions)

    evaluation_metrics[country] = {
        'Linear Regression': {'RMSE': lr_rmse, 'R2': lr_r2},
        'Decision Tree': {'RMSE': dt_rmse, 'R2': dt_r2}
    }

# Display the evaluation metrics
for country, metrics in evaluation_metrics.items():
    print(f"Evaluation metrics for {country}:")
    for model_name, scores in metrics.items():
        print(f"  {model_name}:")
        print(f"    RMSE: {scores['RMSE']:.2f}")
        print(f"    R2: {scores['R2']:.2f}")

"""## Present Predictions

### Subtask:
Display or visualize the predicted emissions from both models.

**Reasoning**:
Create DataFrames from the predicted emissions of both models, convert the 'Year' column to datetime, concatenate with the historical data for the East African countries, and then create a line plot to visualize historical and predicted emissions from both models.
"""

# 1. Create DataFrames from the predicted_emissions dictionaries for both models
predicted_lr_list = []
for country, predictions in predicted_emissions.items():
    for i, emission in enumerate(predictions):
        predicted_lr_list.append({'Country': country, 'Year': future_years[i].year, 'Emissions': emission, 'Model': 'Linear Regression'})

df_predictions_lr = pd.DataFrame(predicted_lr_list)

predicted_dt_list = []
for country, predictions in predicted_dt_emissions.items():
    for i, emission in enumerate(predictions):
        predicted_dt_list.append({'Country': country, 'Year': future_years[i].year, 'Emissions': emission, 'Model': 'Decision Tree'})

df_predictions_dt = pd.DataFrame(predicted_dt_list)


# 2. Convert the 'Year' column in the new DataFrames to datetime objects.
df_predictions_lr['Year'] = pd.to_datetime(df_predictions_lr['Year'], format='%Y')
df_predictions_dt['Year'] = pd.to_datetime(df_predictions_dt['Year'], format='%Y')


# 3. Prepare the historical data for concatenation
df_east_africa_grouped = df_grouped[df_grouped['Country'].isin(east_african_countries)].copy()
df_east_africa_grouped['Year'] = pd.to_datetime(df_east_africa_grouped['Year'], format='%Y')
df_east_africa_grouped['Model'] = 'Historical'


# 4. Concatenate the historical and predictions DataFrames
df_combined_models = pd.concat([df_east_africa_grouped, df_predictions_lr, df_predictions_dt])

# 5. Use matplotlib.pyplot to create a line plot for each country and model
plt.figure(figsize=(15, 7))
for country in east_african_countries:
    df_country = df_combined_models[df_combined_models['Country'] == country]
    for model_name in ['Historical', 'Linear Regression', 'Decision Tree']:
        df_model = df_country[df_country['Model'] == model_name]
        plt.plot(df_model['Year'], df_model['Emissions'], label=f'{country} ({model_name})', linestyle='--' if model_name != 'Historical' else '-')

# 6. Add labels to the x and y axes
plt.xlabel('Year')
plt.ylabel('Emissions/Predicted Emissions')

# 7. Add a title to the plot
plt.title('Historical and Predicted Carbon Emissions for East African Countries (Linear Regression vs Decision Tree)')

# 8. Include a legend
plt.legend()

# 9. Add a grid
plt.grid(True)

# 10. Display the plot
plt.show()